name: uPlanes
main: net.stormdev.uPlanes.main.main
version: 1.0
softdepend: [Vault, uCars]
depend: [ProtocolLib]
commands:
   uPlanes:
        description: This gives uPlanes info
        usage: /<command>
        permission: uplanes.uplanes
        permission-message: You don't have access to this command
        default: true
   plane:
        description: This is an admin command to spawn in uPlanes, etc...
        usage: /<command> give [<Random>]/[<Speed> <Health> <Name>]
        permission: uplanes.admin
        permission-message: You don't have access to this command
        default: true